# Generated by Django 2.2 on 2020-01-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.BooleanField(),
        ),
    ]
