# Generated by Django 2.2 on 2020-01-25 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200124_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='like',
            name='post_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'post_liked')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
